import AppLayout from "@/components/AppLayout/AppLayout";
import React from "react";

const Terms = () => {
  return (
    <AppLayout>
      <section className="relative w-full py-10">
        <div className="container">
          <div className="grid grid-cols-1 gap-y-5">
            <div className="relative">
              <div className="relative w-full text-center mb-5">
                <h2 className="text-4xl font-bold">Terms Of Use</h2>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">1. Terms of Use</h5>
              <div className="space-y-3">
                <p>
                  The use of any product, service or feature accessible on this
                  site by any visitor shall be governed by the following terms
                  of use:
                </p>
                <p>
                  This site is generated by Accurate Securities & Registry
                  Private Limited and shall be used for informational purposes
                  only. By using this site, You hereby agree to abide by the
                  terms and conditions set forth on this page. In the event of
                  You not agreeing to these terms and conditions, You are
                  requested not to use the site.
                </p>
                <p>
                  This site is the property of Accurate Securities & Registry
                  Private Limited and is copyrighted and protected by worldwide
                  copyright laws and treaty provisions. You hereby agree to
                  comply with all copyright laws worldwide in your use of this
                  site and to prevent any unauthorized copying of the site. We
                  do not grant any express or implied rights under any patents,
                  trademarks, copyrights or trade secret information.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">2. Limited License</h5>
              <div className="space-y-3">
                <p>
                  Subject to the terms and conditions set forth in this page,
                  Accurate Securities & Registry Private Limited grants you a
                  non-exclusive, non-transferable, limited right to access, use
                  and display this site. You agree not to interrupt or attempt
                  to interrupt the operation of the site in any manner. Unless
                  otherwise specified, the site is for your personal and
                  non-commercial use. You shall not modify, copy, distribute,
                  transmit, display, perform, reproduce, publish, license,
                  create derivative works from, transfer, or sell any
                  information, products or services obtained from this site.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">
                3. Third Party Content
              </h5>
              <div className="space-y-3">
                <p>
                  The site makes information of third parties available,
                  including articles, analyst reports, tools to facilitate
                  calculation, company information, including any regulatory
                  authority and other data from external sources. You
                  acknowledge and agree that the third party content is not
                  created or endorsed by us.
                </p>
                <p>
                  We make no warranty or representation regarding and do not
                  endorse, any linked sites or the information appearing thereon
                  or any of the products or services described thereon. Links do
                  not imply that we sponsor, endorse, affiliated or associated
                  with, or legally authorized to use any trademark, trade name,
                  logo or copyright symbol displayed in or accessible through
                  the links. You hereby expressly acknowledge and agree that the
                  linked sites are not under the control of us and we are not
                  responsible for the contents of any linked site or any link
                  contained in a linked site, or any changes or updates to such
                  sites. We are providing these links to you only as a
                  convenience, and the inclusion of any link shall not be
                  construed to imply endorsement by us in any manner of the
                  site.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">4. No Warranties</h5>
              <div className="space-y-3">
                <p>
                  This site, the information and any services made available on
                  the site, are provided “as is” without any representation or
                  warranty, express or implied, of any kind, including, but not
                  limited to, warranties of merchantability, non-infringement,
                  or fitness for any particular purpose. There are no warranties
                  of any kind, express or implied, regarding third-party
                  content. In spite of our best endeavors, there is no warranty
                  that this website will be free of any computer viruses.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">
                5. Limitation of Damage
              </h5>
              <div className="space-y-3">
                <p>
                  In no event shall we or our affiliates, our subsidiaries or
                  our joint ventures be liable to any entity for any direct,
                  indirect, special, consequential or other damages (including,
                  without limitation, any lost profits, business interruption,
                  loss of information or programs or other data on your
                  information handling system) that are related to the use of,
                  or the inability to use, the content, materials, and functions
                  of this site or any linked site, even if we are expressly
                  advised of the possibility of such damages.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">6. Disclaimer</h5>
              <div className="space-y-3">
                <p>
                  The site may contain inaccuracies and typographical and
                  clerical errors. We expressly disclaim any obligation(s) to
                  update this site or any of the materials on this site. We do
                  not warrant the accuracy or completeness of the materials or
                  the reliability of any advice, opinion, statement or other
                  information displayed or distributed through the site. You
                  acknowledge that any reliance on any such opinion, advice,
                  statement, memorandum, or information shall be at your sole
                  risk. We reserve the right, in its sole discretion, to correct
                  any errors or omissions in any portion of the site. We may
                  make any other changes to the site, the materials, and the
                  products, programs, services or prices (if any) described in
                  the site at any time without notice. This site is for
                  informational purposes only and should not be construed as
                  technical advice of any manner.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">
                7. Lawful and/or Prohibited Use
              </h5>
              <div className="space-y-3">
                <p>
                  As a condition of your usage of this site, you shall not use
                  the site for any purpose that is unlawful or prohibited by the
                  prevailing rules and regulations. You shall not use the site
                  in any manner that could damage, disable, overburden, or
                  impair our server, or the network connected to our server, or
                  interfere with any other party’s use and enjoyment of any
                  service associated with this site. You shall not attempt to
                  gain unauthorized access to any section of this site, other
                  accounts, computer systems or networks connected to any of our
                  server or to any of the service associated with this site,
                  through hacking, password mining or any other means. You shall
                  not obtain or attempt to obtain any information through any
                  means not intentionally made available through the site.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">8. Indemnity</h5>
              <div className="space-y-3">
                <p>
                  You agree to indemnify and hold harmless Accurate Securities &
                  Registry Private Limited or our affiliates, our subsidiaries
                  or our joint ventures from any claim, cost, expense, judgment
                  or other loss relating to your use of this site in any manner,
                  including without limitation of the foregoing, any action You
                  take which is in violation of the terms and conditions and
                  against the prevailing rules and regulations.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">6. Changes</h5>
              <div className="space-y-3">
                <p>
                  We reserve the rights, at its sole discretion, to change,
                  modify, add or remove any portion of these terms and
                  conditions in whole or in part, at any time. Changes in these
                  terms and conditions will be effective when notice of such
                  change is posted. Your continued use of the site after any
                  changes to these terms and conditions will be considered
                  acceptance of those changes. We may terminate, change, suspend
                  or discontinue any aspect of the site, including the
                  availability of any feature(s) of the website, at any time. We
                  may also impose limits on certain features and services or
                  restrict your access to certain sections or all of the sites
                  without notice or liability. You hereby acknowledge and agree
                  that we may terminate the authorization, rights, and license
                  given above at any point of time at its own sole discretion
                  and upon such termination; You shall immediately destroy all
                  the information downloaded from the site.
                </p>
              </div>
            </div>
            <div className="relative">
              <h5 className="text-xl font-semibold mb-2">
                6. International Users
              </h5>
              <div className="space-y-3">
                <p>
                  This site is controlled, operated and administered by Accurate
                  Securities & Registry Private Limited from its office within
                  India. We make no representation that information on this site
                  is appropriate or available for use at any other location(s)
                  outside India. Any access to this site from territories where
                  their contents are illegal is prohibited. You may not use the
                  site in violation of any prevailing rules and regulations. If
                  You access this site from a location outside India, You are
                  responsible for compliance with all local laws. You agree that
                  the appropriate court in Ahmedabad, India, will have the
                  exclusive jurisdiction to resolve all disputes arising under
                  these terms and conditions and you hereby consent to personal
                  jurisdiction in such forum.
                </p>
                <p>
                  These terms and conditions constitute the entire agreement
                  between Accurate Securities & Registry Private Limited and you
                  with respect to your use of this site. Any claim you may have
                  with respect to your use of this site must be commenced within
                  thirty (30) days of the cause of action. If any provision(s)
                  of this terms and conditions is held by a court of competent
                  jurisdiction to be contrary to law then such provision(s)
                  shall be severed from this terms and conditions and the other
                  remaining provisions of this terms and conditions shall remain
                  in full force and effect. Modified date: Dec 4th, 2024
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </AppLayout>
  );
};

export default Terms;
