import AppLayout from "@/components/AppLayout/AppLayout";
import React from "react";

const Policy = () => {
  return (
    <>
      <title>Privacy Policy</title>
      <AppLayout>
        <section className="relative w-full py-10">
          <div className="container">
            <div className="grid grid-cols-1 gap-y-5">
              <div className="relative">
                <div className="relative w-full text-center mb-5">
                  <h2 className="text-4xl font-bold">Privacy policy</h2>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">
                  1. Privacy Policy
                </h5>
                <div className="space-y-3">
                  <p>
                    Limited data protection is a matter of trust and your
                    privacy is very important to us. We use your information
                    only in the manner set out in this privacy policy. Please
                    read this privacy policy to learn more about our
                    information-gathering and dissemination practices. The
                    privacy practices of this statement apply to services
                    available under this domain, sub-domains and shall apply to
                    generally the websites generated by us, our affiliates, our
                    subsidiaries or our joint ventures if any. By visiting the
                    site, you agree to be bound by the terms and conditions of
                    this privacy policy. This privacy policy explains how we
                    gather information either mandatory or optional as part of
                    the normal business procedure. This detailed privacy policy
                    enables you to make informed decisions in dealings with us.
                  </p>
                  <p>
                    By browsing the website, you acknowledge your acceptance of
                    the terms of this privacy policy and give an express consent
                    to our use and disclosure of your information in accordance
                    with this privacy policy and that any information provided
                    by you through the website is provided under a lawful
                    contract.
                  </p>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">
                  2. Privacy Assurance
                </h5>
                <div className="space-y-3">
                  <p>
                    Your trust and privacy protection are our highest priority.
                    We promise that we will not trade your information with
                    third parties without your explicit consent. From time to
                    time, we may reveal general statistical information about
                    our website visitors, such as a number of visitors, page
                    views, and type of products and services purchased, etc. We
                    may provide the collected information to our affiliates and
                    service providers under contract (such as customer care,
                    data analytics) to support the operation of our business. To
                    some extent, we may use your information to market you.
                  </p>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">
                  3. types of Information
                </h5>
                <div className="space-y-3">
                  <p>
                    In our efforts to continually improve our offerings, we
                    collect and analyze demographic, profile and usage data
                    about the users’ activity on our site. If you choose to post
                    messages on our message boards, chat rooms or other message
                    areas or leave feedback for other users, we retain this
                    information as necessary to resolve disputes, provide
                    customer support and troubleshoot problems as permitted by
                    law. If you send us personal correspondence, such as emails
                    or letters, we may collect such information also. If you
                    register for this site or on another site or use a website
                    providing a services on behalf of us or a website that helps
                    facilitates your activity on this website, that website may
                    provide information about you and your transactions back to
                    us.
                  </p>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">
                  4. Disclosure of Information
                </h5>
                <div className="space-y-3">
                  <p>
                    Your information is an important part of our business and we
                    are not in the business of selling information to others.
                    Our site shares your information only to categories of
                    persons that are either subject to this privacy policy or
                    follow practices as protective as those described in this
                    privacy policy. We share much of our data, including
                    information about you, with our affiliates, our subsidiaries
                    or our joint ventures that are committed to serving your
                    online needs and related services. To the extent that these
                    entities have access to your information, they remain bound
                    by this privacy policy. As we continue to develop our
                    business, we might sell some part of it. In such
                    transactions, your information generally is one of the
                    transferred business assets but remains subject to the
                    promises made in any pre-existing privacy policy.
                  </p>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">5. Legal Request</h5>
                <div className="space-y-3">
                  <p>
                    We cooperate with law enforcement and regulatory inquiries,
                    such as intellectual property rights, fraud, and other
                    rights, to help protect you and the community from bad
                    actors. Therefore, in response to a verified request by law
                    enforcement or other regulatory authorities relating to a
                    criminal investigation or alleged illegal activity, we may
                    (and you authorize us to) disclose some/all of your
                    information as is reasonably necessary to respond to court
                    orders or other legal proceedings.
                  </p>
                </div>
              </div>
              <div className="relative">
                <h5 className="text-xl font-semibold mb-2">
                  6. Instruction Related to Minors
                </h5>
                <div className="space-y-3">
                  <p>
                    Use of this site is available only to persons who can form a
                    legally binding contract. If you are under the age of 18,
                    you cannot use the services of this site. If you wish to do
                    so, such action shall be made by your legal guardian or
                    parents.
                  </p>
                  <p>
                    Our privacy policy is subject to change at any time without
                    notice. To make sure you are aware of any changes, please
                    review this policy periodically.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </AppLayout>
    </>
  );
};

export default Policy;
